CREATE DATABASE budgetapp

CREATE TABLE fact(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    concept VARCHAR(255) NOT NULL,
    amount VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    create_time DATETIME NOT NULL
)ENGINE=InnoDb;